[package]
name = "c8rs-core"
version = "0.1.0"
edition = "2021"

[dependencies]
bitvec = "1.0"
clap = { version = "4.5", features = ["derive"] }
clap-num = "1.1"
log = "0.4"
shlex = "1.3"
spin_sleep_util = "0.1"
